const motivationalQuotes = [
  "The secret of getting ahead is getting started. - Mark Twain",
  "Discipline is the bridge between goals and accomplishment. - Jim Rohn",
  "Well done is better than well said. - Benjamin Franklin",
  "A little progress each day adds up to big results. - Diana Martin",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "You are what you repeatedly do. Excellence, then, is not an act, but a habit. - Will Durant",
  "One day or day one. You decide.",
  "Dream big and dare to fail. - Norman Vaughan",
  "Hard work beats talent when talent doesn't work hard. - Tim Notke",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Don't limit your challenges. Challenge your limits.",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Success doesn't just find you. You have to go out and get it.",
  "Your limitation—it's only your imagination.",
  "Do something today that your future self will thank you for. - Sean Patrick Flanery",
  "Little things make big days.",
  "Dream it. Wish it. Do it.",
  "Stay focused and never give up.",
  "Work hard in silence, let your success be your noise. - Frank Ocean",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction. - George Horace Lorimer",
  "Do what you can with all you have, wherever you are. - Theodore Roosevelt",
  "The future depends on what you do today. - Mahatma Gandhi",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "Act as if what you do makes a difference. It does. - William James",
  "Quality is not an act, it is a habit. - Will Durant",
  "The best way to predict the future is to create it. - Abraham Lincoln",
  "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
  "The difference between ordinary and extraordinary is that little extra. - Jimmy Johnson",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "Don’t wait. The time will never be just right. - Napoleon Hill",
  "If you want to achieve greatness stop asking for permission.",
  "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The man who has confidence in himself gains the confidence of others. - Hasidic Proverb",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
  "Don’t let yesterday take up too much of today. - Will Rogers",
  "You miss 100% of the shots you don’t take. - Wayne Gretzky",
  "Failure will never overtake me if my determination to succeed is strong enough. - Og Mandino",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn"
];

export function getRandomQuote() {
  return motivationalQuotes[Math.floor(Math.random() * motivationalQuotes.length)];
}